# Generated by Django 4.0 on 2021-12-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
